# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1014, 782)
        MainWindow.setStyleSheet("background-color: rgb(185, 217, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setGeometry(QtCore.QRect(540, 600, 151, 61))
        self.startButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 75 16pt \"Nirmala UI\";")
        self.startButton.setObjectName("startButton")
        self.stopButton = QtWidgets.QPushButton(self.centralwidget)
        self.stopButton.setGeometry(QtCore.QRect(760, 600, 151, 61))
        self.stopButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 75 16pt \"Nirmala UI\";")
        self.stopButton.setObjectName("stopButton")
        self.tableText = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.tableText.setGeometry(QtCore.QRect(0, 140, 1011, 381))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tableText.setFont(font)
        self.tableText.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 12pt \"Lucida Sans\";")
        self.tableText.setReadOnly(True)
        self.tableText.setPlainText("")
        self.tableText.setCenterOnScroll(False)
        self.tableText.setObjectName("tableText")
        self.routingLabel = QtWidgets.QLabel(self.centralwidget)
        self.routingLabel.setGeometry(QtCore.QRect(450, 100, 151, 31))
        self.routingLabel.setStyleSheet("font: 12pt \"Lucida Sans\";")
        self.routingLabel.setObjectName("routingLabel")
        self.titleLabel = QtWidgets.QLabel(self.centralwidget)
        self.titleLabel.setGeometry(QtCore.QRect(450, -20, 211, 91))
        self.titleLabel.setStyleSheet("font: 63 36pt \"Lucida Sans\";\n"
"text-decoration: underline;")
        self.titleLabel.setObjectName("titleLabel")
        self.spinBoxUpdateTime = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBoxUpdateTime.setGeometry(QtCore.QRect(310, 540, 101, 41))
        self.spinBoxUpdateTime.setStyleSheet("font: 12pt \"Lucida Sans\";\n"
"background-color: rgb(255, 255, 255);")
        self.spinBoxUpdateTime.setMinimum(15)
        self.spinBoxUpdateTime.setMaximum(40)
        self.spinBoxUpdateTime.setProperty("value", 30)
        self.spinBoxUpdateTime.setObjectName("spinBoxUpdateTime")
        self.spinBoxTimeout = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBoxTimeout.setGeometry(QtCore.QRect(310, 600, 101, 41))
        self.spinBoxTimeout.setStyleSheet("font: 12pt \"Lucida Sans\";\n"
"background-color: rgb(255, 255, 255);")
        self.spinBoxTimeout.setMinimum(20)
        self.spinBoxTimeout.setMaximum(200)
        self.spinBoxTimeout.setProperty("value", 180)
        self.spinBoxTimeout.setObjectName("spinBoxTimeout")
        self.spinBoxGarbageTime = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBoxGarbageTime.setGeometry(QtCore.QRect(310, 660, 101, 41))
        self.spinBoxGarbageTime.setStyleSheet("font: 12pt \"Lucida Sans\";\n"
"background-color: rgb(255, 255, 255);")
        self.spinBoxGarbageTime.setMinimum(20)
        self.spinBoxGarbageTime.setMaximum(300)
        self.spinBoxGarbageTime.setProperty("value", 240)
        self.spinBoxGarbageTime.setObjectName("spinBoxGarbageTime")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(170, 540, 131, 41))
        self.label.setStyleSheet("font: 12pt \"Lucida Sans\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(200, 610, 91, 31))
        self.label_2.setStyleSheet("font: 12pt \"Lucida Sans\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(70, 670, 221, 31))
        self.label_3.setStyleSheet("font: 12pt \"Lucida Sans\";")
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1014, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.startButton.setText(_translate("MainWindow", "Start"))
        self.stopButton.setText(_translate("MainWindow", "Stop"))
        self.routingLabel.setText(_translate("MainWindow", "Routing table"))
        self.titleLabel.setText(_translate("MainWindow", "RIP v2"))
        self.label.setText(_translate("MainWindow", "Update time"))
        self.label_2.setText(_translate("MainWindow", "Timeout"))
        self.label_3.setText(_translate("MainWindow", "Garbage colector time"))
