# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1067, 866)
        MainWindow.setStyleSheet("background-color: rgb(185, 217, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setGeometry(QtCore.QRect(340, 740, 151, 61))
        self.startButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 75 16pt \"Nirmala UI\";")
        self.startButton.setObjectName("startButton")
        self.stopButton = QtWidgets.QPushButton(self.centralwidget)
        self.stopButton.setGeometry(QtCore.QRect(540, 740, 151, 61))
        self.stopButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 75 16pt \"Nirmala UI\";")
        self.stopButton.setObjectName("stopButton")
        self.tableText = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.tableText.setGeometry(QtCore.QRect(30, 140, 1011, 381))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tableText.setFont(font)
        self.tableText.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 12pt \"Lucida Sans\";")
        self.tableText.setReadOnly(True)
        self.tableText.setPlainText("")
        self.tableText.setCenterOnScroll(False)
        self.tableText.setObjectName("tableText")
        self.sendFirstButton = QtWidgets.QRadioButton(self.centralwidget)
        self.sendFirstButton.setGeometry(QtCore.QRect(660, 580, 121, 31))
        self.sendFirstButton.setStyleSheet("font: 12pt \"Lucida Sans\";")
        self.sendFirstButton.setObjectName("sendFirstButton")
        self.sendAllButton = QtWidgets.QRadioButton(self.centralwidget)
        self.sendAllButton.setGeometry(QtCore.QRect(660, 630, 191, 20))
        self.sendAllButton.setStyleSheet("font: 12pt \"Lucida Sans\";")
        self.sendAllButton.setChecked(True)
        self.sendAllButton.setObjectName("sendAllButton")
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(790, 580, 71, 31))
        self.spinBox.setStyleSheet("font: 11pt \"Lucida Sans\";")
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(5)
        self.spinBox.setProperty("value", 2)
        self.spinBox.setObjectName("spinBox")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(870, 580, 81, 31))
        self.label.setStyleSheet("font: 12pt \"Lucida Sans\";")
        self.label.setObjectName("label")
        self.detailsLabel = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.detailsLabel.setGeometry(QtCore.QRect(30, 570, 291, 51))
        self.detailsLabel.setStyleSheet("font: italic 9pt \"Lucida Sans\";")
        self.detailsLabel.setObjectName("detailsLabel")
        self.timerSpinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.timerSpinBox.setGeometry(QtCore.QRect(390, 570, 91, 41))
        self.timerSpinBox.setStyleSheet("font: 12pt \"Lucida Sans\";\n"
"background-color: rgb(255, 255, 255);")
        self.timerSpinBox.setMinimum(2)
        self.timerSpinBox.setMaximum(10)
        self.timerSpinBox.setObjectName("timerSpinBox")
        self.maxHopSpinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.maxHopSpinBox.setGeometry(QtCore.QRect(390, 650, 91, 41))
        self.maxHopSpinBox.setStyleSheet("font: 12pt \"Lucida Sans\";\n"
"background-color: rgb(255, 255, 255);")
        self.maxHopSpinBox.setMinimum(1)
        self.maxHopSpinBox.setMaximum(15)
        self.maxHopSpinBox.setProperty("value", 2)
        self.maxHopSpinBox.setObjectName("maxHopSpinBox")
        self.baseTimeLabel = QtWidgets.QLabel(self.centralwidget)
        self.baseTimeLabel.setGeometry(QtCore.QRect(380, 540, 111, 21))
        self.baseTimeLabel.setStyleSheet("font: 12pt \"Lucida Sans\";")
        self.baseTimeLabel.setObjectName("baseTimeLabel")
        self.HopLabel = QtWidgets.QLabel(self.centralwidget)
        self.HopLabel.setGeometry(QtCore.QRect(370, 620, 161, 21))
        self.HopLabel.setStyleSheet("font: 12pt \"Lucida Sans\";")
        self.HopLabel.setObjectName("HopLabel")
        self.routingLabel = QtWidgets.QLabel(self.centralwidget)
        self.routingLabel.setGeometry(QtCore.QRect(450, 100, 151, 31))
        self.routingLabel.setStyleSheet("font: 12pt \"Lucida Sans\";")
        self.routingLabel.setObjectName("routingLabel")
        self.titleLabel = QtWidgets.QLabel(self.centralwidget)
        self.titleLabel.setGeometry(QtCore.QRect(450, -20, 211, 91))
        self.titleLabel.setStyleSheet("font: 63 36pt \"Lucida Sans\";\n"
"text-decoration: underline;")
        self.titleLabel.setObjectName("titleLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1067, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.startButton.setText(_translate("MainWindow", "Start"))
        self.stopButton.setText(_translate("MainWindow", "Stop"))
        self.sendFirstButton.setText(_translate("MainWindow", "Send first"))
        self.sendAllButton.setText(_translate("MainWindow", "Send all entries"))
        self.label.setText(_translate("MainWindow", "entries"))
        self.detailsLabel.setPlainText(_translate("MainWindow", "ROUTE_TIMEOUT = BASE_TIMER * 6\n"
"DELETE_TIMEOUT = BASE_TIMER * 4"))
        self.baseTimeLabel.setText(_translate("MainWindow", "Base time"))
        self.HopLabel.setText(_translate("MainWindow", "Max hop count"))
        self.routingLabel.setText(_translate("MainWindow", "Routing table"))
        self.titleLabel.setText(_translate("MainWindow", "RIP v2"))
